### ISSUE TITLE
Feature Request: Fill screen

### ISSUE THREAD

**Issue by onderbakirtas** [henrygd/bigpicture#61]
Hello, and thanks for the plugin. I think there can be an option to make the image fill the screen width/height (like `background-size: contain`).

**Comment by henrygd** [comment]
Try putting this in your css:

```css
#bp_container img {
    max-height: 100%!important;
    max-width: 100%!important;
}
```
